### ISSUE TITLE
pTexture.cpp doesn't compile on Mac OS X 10.7 using OpenGL/gl3.h

### ISSUE THREAD

**Issue by mplanck** [PixarAnimationStudios/OpenSubdiv#54]
os: mac os 10.7.4
gpu: ATI Radeon HD 4850 (iMac)

I'm seeing a problem when compiling the opensubdiv source on my Mac with hopes of using my locally built ptex, cuda, and openCL, library.  I'm disabling all maya packages by excluding find_package(maya).  

Looks like the recent change to take glew out of the APPLE builds is causing extension support problems for pTexture.  

/Users/mplanck/Dropbox/Public/DevelopmentProjects/git-repos/OpenSubdiv/opensubdiv/osd/pTexture.cpp:1000: error: ‘GL_HALF_FLOAT_ARB’ was not declared in this scope
/Users/mplanck/Dropbox/Public/DevelopmentProjects/git-repos/OpenSubdiv/opensubdiv/osd/pTexture.cpp:1006: error: ‘GL_LUMINANCE’ was not declared in this scope
/Users/mplanck/Dropbox/Public/DevelopmentProjects/git-repos/OpenSubdiv/opensubdiv/osd/pTexture.cpp:1007: error: ‘GL_LUMINANCE_ALPHA’ was not declared in this scope
make[2]: **\* [opensubdiv/osd/CMakeFiles/osd_dynamic.dir/pTexture.cpp.o] Error 1

When I re-add the use of GL/glew.h (1.9.0) where OpenGL/gl3.h is used, I'm able to get the glutViewer working but without ptexture support (have to comment glGenBuffers in mesh.cpp line 198).  My gl3.h was last updated:
- gl3.h last updated on $Date: 2010/12/14 02:44:48 $

I looked at the most recent gl3.h I could find on opengl.org and it is different but doesn't seem to add support for these defines.  Any help is appreciated.

Here's the output of my cmake from scratch:

-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Developer/usr/bin/gcc
-- Check for working C compiler: /Developer/usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /Developer/usr/bin/c++
-- Check for working CXX compiler: /Developer/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Compiling OpenSubdiv version 0.1.0
-- Using cmake version 2.8.3
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp 
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework 
-- Found CUDA: /usr/local/cuda (found version "4.2")
-- Found GLUT: /System/Library/Frameworks/GLUT.framework/Headers 
-- Found PTEX: /usr/local/include 
CMake Warning at CMakeLists.txt:138 (message):
  OpenGL was not found : support for GLSL parallel compute kernels will be
  disabled in Osd.  If you have an OpenGL SDK installed (version 4.2 or
  above), please refer to the FindOpenGL.cmake shared module in your cmake
  installation.

CMake Warning at CMakeLists.txt:186 (message):
  Maya was not found : the OpenSubdiv mayaViwer plugin will not be available.
  If you do have Maya installed and see this message, please add your Maya
  path to FindMaya.cmake in
  /Users/mplanck/Dropbox/Public/DevelopmentProjects/git-repos/OpenSubdiv/cmake
  or set it through the MAYA_LOCATION cmake command line argument or
  environment variable.

CMake Warning at regression/CMakeLists.txt:79 (message):
  The following libraries could not be found : glew.  The osd regression test
  will not be available.  If you have these libraries installed, please
  specify their path to cmake (through the GLEW_LOCATION and GLUT_LOCATION
  command line arguments or environment variables).

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mplanck/Dropbox/Public/DevelopmentProjects/git-repos/OpenSubdiv/build
